### ISSUE TITLE
Cannot update opossum.lib.hs submodule

### ISSUE THREAD

**Issue by dd-jy** [opossum-tool/aioc#2]
I ran the build-docker-image.sh script file, but it failed to update submodules.
```
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path ' opossum.lib.hs'
```
Please fix to update main branch for opossum.lib.hs.

**Comment by maxhbr** [comment]
Hey @dd-jy ,

I just tried to reproduce the issue but it worked for me.

I am surprised by two things:
- it should be `origin/main` instead of `origin/master` and
- there is a space in the string `' opossum.lib.hs'`.

Could you answer some questions to give me more context and to pin the error to the specific line in the script.

- what operating system do you use?
- can you run the following two commands in the root of the repository and tell me whether they succeed and what the output is:
  - `git submodule init`
  - `git submodule update --remote`


additionally I will pin the branch in https://github.com/opossum-tool/aioc/blob/main/.gitmodules to be sure.

**Comment by maxhbr** [comment]
could not be reproduced.
